#! /usr/local/bin/zsh

# update PS1
function preexec() {
    PS1_EXECUTING_CMD=1
    PS1_START_TIME=`date +%s`
}

LINENUM=0
function precmd() {
    # printing the error code if the last line ended in an error
    local errorcode="$?"
    if [ ${errorcode} != 0 ]; then
        echo "\e[90m╰─❰\e[1;31merror $errorcode\e[90m❱\n\e[39;0m"
    fi

    # printing the time it took to run the last command
    local end_time=`date +%s`;
    local runtime=$((end_time-PS1_START_TIME)) # yeah millisecond not exact but speed more important
    if [[ -v PS1_START_TIME ]] && [[ $PS1_START_TIME -gt 0 ]] && [[ $runtime -gt 5 ]] && [[ $PS1_EXECUTING_CMD -eq 1 ]]; then
        tput bel
        sleep .3
        tput bel
    fi
    PS1_EXECUTING_CMD=0
}



